// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdewvepgbmjsomidjuto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZXd2ZXBnYm1qc29taWRqdXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTMwMzUsImV4cCI6MjA2ODQyOTAzNX0.p4THVYZ3j9GVFJdEZo5e6koHFIs2_IrI31vP3tAC4Jk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});